services:
  # ----------------------------------------
  # CONTAINER 1: the frontend
  # ----------------------------------------
  webapp:
    build: .
    container_name: frontend
    ports:
      - "5000:5000"
    command: uv run run_web.py # <-- Startet NUR Flask
    env_file: .env
    environment:
      - WORKSPACE=/coding-agent-workspace
    volumes:
      - workspace:/coding-agent-workspace
      - ./app/instance:/coding-agent/app/instance

  # ----------------------------------------
  # CONTAINER 2: the AI coding agent
  # ----------------------------------------
  ai-coding-agent:
    build: .
    container_name: ai-coding-agent
    command: uv run run_agent.py
    env_file: .env
    environment:
      - WORKSPACE=/coding-agent-workspace
      - WORKBENCH_WORKSPACE=/coding-agent-workspace
    volumes:
      - ./app/instance:/coding-agent/app/instance
      - workspace:/coding-agent-workspace
      # the socket to connect to the docker daemon
      - /var/run/docker.sock:/var/run/docker.sock

  # ----------------------------------------
  # CONTAINER 3: the workbench
  # ----------------------------------------
  workbench-backend:
    build:
      context: .
      dockerfile: Dockerfile.java-node
    container_name: workbench-backend
    depends_on:
      cleancoda-docker-host:
        condition: service_healthy
    network_mode: "service:cleancoda-docker-host"
    environment:
      DOCKER_HOST: tcp://localhost:2375
      # needed, because localhost meets with localhost this container
      # not the docker host
      TESTCONTAINERS_HOST_OVERRIDE: cleancoda-docker-host
      DOCKER_TLS_VERIFY: ""
      DOCKER_CERT_PATH: ""
    # workspace directory where commands are executed
    working_dir: /coding-agent-workspace
    volumes:
      # Maven Cache (makes tests faster)
      - maven-cache:/root/.m2
      # Gradle Cache (makes tests faster)
      - gradle-cache:/root/.gradle
      # Workspace directory
      - workspace:/coding-agent-workspace
    tty: true

  # ----------------------------------------
  # CONTAINER 4: the docker host
  # ----------------------------------------
  cleancoda-docker-host:
    image: docker:27-dind
    container_name: cleancoda-docker-host
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - docker-data:/var/lib/docker
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 10s
      timeout: 5s
      retries: 6

volumes:
  docker-data:
    driver: local
  workspace:
    driver: local
  maven-cache:
    driver: local
  gradle-cache:
    driver: local
