services:
  # ----------------------------------------
  # CONTAINER 1: the frontend
  # ----------------------------------------
  webapp:
    build: .
    container_name: frontend
    ports:
      - "5000:5000"
    command: uv run run_web.py # <-- Startet NUR Flask
    env_file: .env
    environment:
      - WORKSPACE=/coding-agent-workspace
    volumes:
      - ./workspace:/coding-agent-workspace
      - ./app/instance:/coding-agent/app/instance

  # ----------------------------------------
  # CONTAINER 2: the AI coding agent
  # ----------------------------------------
  ai-coding-agent:
    build: .
    container_name: ai-coding-agent
    command: uv run run_agent.py
    env_file: .env
    environment:
      - WORKSPACE=/coding-agent-workspace
    volumes:
      - ./app/instance:/coding-agent/app/instance
      # mapping ./workspace to /workspace in container
      - ./workspace:/coding-agent-workspace
      # the socket to connect to the docker daemon
      - /var/run/docker.sock:/var/run/docker.sock

  # ----------------------------------------
  # CONTAINER 3: the workbench
  # ----------------------------------------
  workbench-backend:
    image: maven:3.9-eclipse-temurin-21
    container_name: workbench-backend
    # this command keeps the container alive
    command: tail -f /dev/null
    # in which workspace=working_dir the commands are executed
    working_dir: /coding-agent-workspace
    volumes:
      # HIER: Exakt gleicher Pfad wie beim Agenten, damit Pfad-Befehle stimmen
      - ./workspace:/coding-agent-workspace
      # Optional: Maven Cache (macht Tests schneller)
      - ~/.m2:/root/.m2
      # the socket to connect to the docker daemon
      - /var/run/docker.sock:/var/run/docker.sock
