from typing import Any


class Memory:
    """Manages in-memory chat message history for LLM interactions.

    Serves as the base memory handler for agents, storing conversation history in-memory
    as a list of role-based message dictionaries. Supports standard role helpers
    (system, user, assistant, tool), list-like access/iteration, and provides a hook
    `_save_memory()` for subclasses requiring persistence.
    """

    def __init__(
        self,
        system_prompt: str | None = None,
        initial_messages: list[dict[str, Any] | Any] | None = None,
    ) -> None:
        """Initializes the Memory instance.

        Args:
            system_prompt: Optional initial system prompt string to add as the first message.
            initial_messages: Optional list of initial message dictionaries or objects to populate memory.
        """
        self._messages: list[dict[str, Any] | Any] = []
        if system_prompt:
            self.add_system(system_prompt)
        if initial_messages:
            for msg in initial_messages:
                self.add_message(msg)

        self._save_memory()

    def _save_memory(self) -> None:
        """Saves memory state. Base implementation is a no-op hook for in-memory storage."""
        pass

    @property
    def messages(self) -> list[dict[str, Any] | Any]:
        """Returns the list of stored chat messages."""
        return self._messages

    def _message_to_dict(self, message: Any) -> dict[str, Any]:
        """Converts a message object or dictionary into a standardized dictionary representation.

        Args:
            message: Raw dictionary, Pydantic model, or custom message object.

        Returns:
            dict[str, Any]: Dictionary containing role and content (and optional tool_calls).
        """
        if isinstance(message, dict):
            return message
        if hasattr(message, "model_dump") and callable(message.model_dump):
            return message.model_dump()
        if hasattr(message, "dict") and callable(message.dict):
            return message.dict()
        if hasattr(message, "__dict__"):
            return {k: v for k, v in message.__dict__.items() if not k.startswith("_")}
        role = getattr(message, "role", "unknown")
        content = getattr(message, "content", str(message))
        return {"role": role, "content": content}

    def add_message(self, message: dict[str, Any] | Any) -> None:
        """Adds a raw message object or dictionary to memory and triggers save hook.

        Args:
            message: Message object or dictionary to append.
        """
        self._messages.append(message)
        self._save_memory()

    def add_system(self, content: str) -> None:
        """Adds a system message to memory.

        Args:
            content: System prompt or directive text.
        """
        self.add_message({"role": "system", "content": content})

    def add_user(self, content: str) -> None:
        """Adds a user message to memory.

        Args:
            content: User query or prompt text.
        """
        self.add_message({"role": "user", "content": content})

    def add_assistant(
        self, content: str | None = None, tool_calls: list[Any] | None = None
    ) -> None:
        """Adds an assistant response message to memory.

        Args:
            content: Optional textual response from the assistant.
            tool_calls: Optional list of tool calls generated by the assistant.
        """
        msg: dict[str, Any] = {"role": "assistant", "content": content}
        if tool_calls is not None:
            msg["tool_calls"] = tool_calls
        self.add_message(msg)

    def add_tool_result(self, tool_call_id: str, content: str) -> None:
        """Adds a tool execution result message to memory.

        Args:
            tool_call_id: Unique identifier matching the assistant's tool call request.
            content: Execution result or error text returned by the tool.
        """
        self.add_message({
            "role": "tool",
            "tool_call_id": tool_call_id,
            "content": content,
        })

    # Aliases for convenience
    add_system_message = add_system
    add_user_message = add_user
    add_assistant_message = add_assistant
    add_tool_message = add_tool_result

    def get_messages(self) -> list[dict[str, Any] | Any]:
        """Returns a shallow copy of all stored messages.

        Returns:
            list[dict[str, Any] | Any]: Copy of the message history.
        """
        return list(self._messages)

    def clear(self, keep_system: bool = True) -> None:
        """Clears memory content.

        Args:
            keep_system: If True, preserves system role messages while clearing all others.
                If False, wipes all stored messages.
        """
        if keep_system:
            self._messages = [
                msg for msg in self._messages
                if (isinstance(msg, dict) and msg.get("role") == "system")
                or getattr(msg, "role", None) == "system"
            ]
        else:
            self._messages.clear()
        self._save_memory()

    def append(self, message: dict[str, Any] | Any) -> None:
        """Appends a message to memory (provides list-like append interface).

        Args:
            message: Message object or dictionary to add.
        """
        self.add_message(message)

    def __len__(self) -> int:
        return len(self._messages)

    def __getitem__(self, index: int) -> dict[str, Any] | Any:
        return self._messages[index]

    def __iter__(self):
        return iter(self._messages)

    def __repr__(self) -> str:
        return f"Memory(messages_count={len(self._messages)})"
